CREATE TABLE kins (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    icon INTEGER NOT NULL,
    CHECK (name <> ''),
    FOREIGN KEY (icon) REFERENCES icons(id)
);
