INSERT INTO professions (name, icon, description) VALUES
    ($val$Artisan$val$, (SELECT id FROM icons WHERE name = $val$anvil$val$ LIMIT 1), $val$Proud makers who turn raw matter into useful order, from bridges and homes to tools, weapons, and leather armor. Their practical craft makes them valued in every village.$val$),
    ($val$Bard$val$, (SELECT id FROM icons WHERE name = $val$lyre$val$ LIMIT 1), $val$Singers, musicians, and storytellers preserve ancient deeds and carry new ones forward in song. They roam markets and inns or perform for the powerful, always seeking a tale worth making immortal.$val$),
    ($val$Fighter$val$, (SELECT id FROM icons WHERE name = $val$diamond-hilt$val$ LIMIT 1), $val$Weapon specialists earn their living by violence, whether with sword, spear, or crossbow. Some value clean efficiency over bloodshed, while others bear hard memories from lives spent near death.$val$),
    ($val$Hunter$val$, (SELECT id FROM icons WHERE name = $val$high-shot$val$ LIMIT 1), $val$Hunters stalk and snare prey in the wild, treating its death and every useful part as a sacred responsibility. The harsh wilderness is their true home, though its solitude can make society difficult.$val$),
    ($val$Knight$val$, (SELECT id FROM icons WHERE name = $val$mounted-knight$val$ LIMIT 1), $val$Warriors bound by an oath to an order, lord, god, or another higher cause. Its rules guide every thought and deed, and many devote themselves to defending a person or place.$val$),
    ($val$Mage$val$, (SELECT id FROM icons WHERE name = $val$crystal-wand$val$ LIMIT 1), $val$Mages study the ancient forces that run through nature and the world, following schools with very different theories of magic and its source.$val$),
    ($val$Mariner$val$, (SELECT id FROM icons WHERE name = $val$saber-and-pistol$val$ LIMIT 1), $val$Sailors and waterfolk belong to the waves, rivers, and lakes, bound to the water by love, respect, and dread. Their trade ranges from pirates and ferrymen to whalers, explorers, and captains.$val$),
    ($val$Merchant$val$, (SELECT id FROM icons WHERE name = $val$locked-chest$val$ LIMIT 1), $val$Merchants turn what they have into more, buying cheaply and selling dearly. They run settled shops or travel with caravans and adventurers in search of markets, customers, and rare goods.$val$),
    ($val$Scholar$val$, (SELECT id FROM icons WHERE name = $val$scroll-unfurled$val$ LIMIT 1), $val$Scholars pursue knowledge of nature, forgotten history, and the hidden structures of the world. They seek sources in the field, from monster lore and plants to ancient languages and lost scripts.$val$),
    ($val$Thief$val$, (SELECT id FROM icons WHERE name = $val$assassin-pocket$val$ LIMIT 1), $val$Professional takers of other people’s property include burglars, pickpockets, charlatans, and highwaymen. Some work through guilds and quiet guile, while others favor blades and the night.$val$);
